# Generated by Django 4.1.7 on 2023-03-22 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworldapp', '0002_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='id',
            field=models.CharField(max_length=100, primary_key=120, serialize=False),
        ),
    ]
