# Generated by Django 4.1.7 on 2023-03-22 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworldapp', '0003_alter_person_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=100, serialize=False)),
                ('class_name', models.CharField(max_length=254, unique=True)),
                ('floor', models.CharField(max_length=100)),
                ('date_joined', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'classes',
                'db_table': 'class',
            },
        ),
        migrations.AlterField(
            model_name='person',
            name='id',
            field=models.CharField(max_length=100, primary_key=100, serialize=False),
        ),
    ]
